/*
 * @作者: 14770137
 * @Date: 2022-11-03 18:21:55
 */
import type { SidebarConfig } from '@vuepress/theme-default'

const sidebar:SidebarConfig =  {
    '/js/':[
        {
            text:'JavaScript',
            children:[
                '/js/README.md',
                '/js/Math.md',
                '/js/CircleCollision.md',
                '/js/canvasClock.md',
                '/js/canvas.md'
            ]
        }
    ],
    '/C++/':[
        {
            text:'C++',
            children:[
                '/C++/readme.md',
                '/C++/cmake.md',
                '/C++/vcpkg.md'
            ]
        }
    ],
    '/css/':[
        {
            text:'css',
            children:[
                '/css/flex.md',
                '/css/scss.md',
            ]
        }
    ],
    '/git/':[
        {
            text:'git',
            children:[
                '/git/readme.md',
                '/git/action.md'
            ]
        }
    ],
    '/typescript/':[
        {
            text:'TS',
            children:[
                '/typescript/readme.md',
                '/typescript/class.md',
                '/typescript/constructSign.md',
                '/typescript/crossType.md',
                '/typescript/enum.md',
                '/typescript/function.md',
                '/typescript/Generic.md',
                '/typescript/identifier.md',
                '/typescript/interface.md',
                '/typescript/mapping.md',
                '/typescript/predicate.md',
                '/typescript/stringType.md',
                '/typescript/type.md',
                '/typescript/union.md',
            ]
        }
    ],
    '/Vue/':[
        {
            text:'Vue.js',
            children:[
                '/Vue/readme.md',
                '/Vue/router.md',
                '/Vue/V-model.md',
                '/Vue/vuepress.md'
            ]
        }
    ],
    '/markdown/':[
        {
            text:'markDown',
            children:[
                '/markdown/README.md'
            ]
        }
    ],
    '/kotlin/':[
        {
            text:'kotlin入门',
            children:[
                '/kotlin/README.md'
            ]
        }
    ],
    '/CSharp/':[
        {
            text:'C#入门',
            children:[
                '/CSharp/README.md'
            ]
        },
        {
            text:'linq',
            children:[
                '/CSharp/Linq.md'
            ]
        }
    ]
}
export default sidebar;